-- Create the database (if it doesn't exist)
CREATE DATABASE IF NOT EXISTS crash_data;

-- Use the crash_data database
USE crash_data;

-- Create the crashes table
CREATE TABLE crashes (
    CRASH_DATE DATE,
    CRASH_TIME TIME,
    BOROUGH VARCHAR(50),
    ZIP_CODE INT,
    LATITUDE FLOAT,
    LONGITUDE FLOAT,
    LOCATION VARCHAR(100),
    ON_STREET_NAME VARCHAR(100),
    CROSS_STREET_NAME VARCHAR(100),
    OFF_STREET_NAME VARCHAR(100),
    NUMBER_OF_PERSONS_INJURED INT,
    NUMBER_OF_PERSONS_KILLED INT,
    NUMBER_OF_PEDESTRIANS_INJURED INT,
    NUMBER_OF_PEDESTRIANS_KILLED INT,
    NUMBER_OF_CYCLIST_INJURED INT,
    NUMBER_OF_CYCLIST_KILLED INT,
    NUMBER_OF_MOTORIST_INJURED INT,
    NUMBER_OF_MOTORIST_KILLED INT,
    COLLISION_ID INT PRIMARY KEY,
    VEHICLE_TYPE_CODE_1 VARCHAR(50),
    VEHICLE_TYPE_CODE_2 VARCHAR(50),
    VEHICLE_TYPE_CODE_3 VARCHAR(50),
    VEHICLE_TYPE_CODE_4 VARCHAR(50),
    VEHICLE_TYPE_CODE_5 VARCHAR(50),
    CONTRIBUTING_FACTORS VARCHAR(200)
);

-- Create the person table
CREATE TABLE person (
    UNIQUE_ID INT,
    COLLISION_ID INT,
    CRASH_DATE DATE,
    CRASH_TIME TIME,
    PERSON_ID VARCHAR(50),
    PERSON_TYPE VARCHAR(50),
    PERSON_INJURY VARCHAR(50),
    VEHICLE_ID INT,
    PERSON_AGE INT,
    EJECTION VARCHAR(50),
    EMOTIONAL_STATUS VARCHAR(50),
    BODILY_INJURY VARCHAR(50),
    POSITION_IN_VEHICLE VARCHAR(100),
    SAFETY_EQUIPMENT VARCHAR(50),
    PED_LOCATION VARCHAR(50),
    PED_ACTION VARCHAR(50),
    COMPLAINT VARCHAR(50),
    PED_ROLE VARCHAR(50),
    CONTRIBUTING_FACTOR_1 VARCHAR(100),
    CONTRIBUTING_FACTOR_2 VARCHAR(100),
    PERSON_SEX VARCHAR(10),
    PRIMARY KEY (UNIQUE_ID, COLLISION_ID),
    FOREIGN KEY (COLLISION_ID) REFERENCES crashes(COLLISION_ID)
);

-- Create the vehicles table
CREATE TABLE vehicles (
    UNIQUE_ID INT,
    COLLISION_ID INT,
    CRASH_DATE DATE,
    CRASH_TIME TIME,
    VEHICLE_ID VARCHAR(50),
    STATE_REGISTRATION VARCHAR(50),
    VEHICLE_TYPE VARCHAR(50),
    VEHICLE_MAKE VARCHAR(50),
    VEHICLE_MODEL VARCHAR(50),
    VEHICLE_YEAR INT,
    TRAVEL_DIRECTION VARCHAR(50),
    VEHICLE_OCCUPANTS INT,
    DRIVER_LICENSE_STATUS VARCHAR(50),
    DRIVER_LICENSE_JURISDICTION VARCHAR(50),
    PRE_CRASH VARCHAR(50),
    POINT_OF_IMPACT VARCHAR(50),
    VEHICLE_DAMAGE VARCHAR(50),
    VEHICLE_DAMAGE_1 VARCHAR(50),
    VEHICLE_DAMAGE_2 VARCHAR(50),
    VEHICLE_DAMAGE_3 VARCHAR(50),
    PUBLIC_PROPERTY_DAMAGE VARCHAR(50),
    PUBLIC_PROPERTY_DAMAGE_TYPE VARCHAR(50),
    CONTRIBUTING_FACTOR_1 VARCHAR(100),
    CONTRIBUTING_FACTOR_2 VARCHAR(100),
    PRIMARY KEY (UNIQUE_ID, COLLISION_ID),
    FOREIGN KEY (COLLISION_ID) REFERENCES crashes(COLLISION_ID)
);




select count(*) from crashes



SET FOREIGN_KEY_CHECKS = 0;
